# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Journal
tagline:          '... of an Engineer'
description:      '... of an Engineer'
url:              soumyakbhattacharyya.github.io
baseurl:          /

author:
  name:           'Soumyak Bhattacharyya'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/soumyakbhattacharyya
